version: '3.8'
services:
  db:
    container_name: meet_your_mentor_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=mym
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: